name: Run Tests

on:
  push:
    branches: [ '**' ]  # Run on any branch push
  pull_request:
    branches: [ '**' ]  # Run on PRs to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
    
    - name: Run benchmarks
      run: npm run bench || true  # Continue even if benchmarks fail
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          bench-results.json
          vitest.results.json
        retention-days: 30